//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjusterSettingsPayroll
    {
        public int SettingsPayrollId { get; set; }
        public Nullable<int> AdjusterId { get; set; }
        public string Rating { get; set; }
        public Nullable<int> QAScore { get; set; }
        public string Designation { get; set; }
        public Nullable<int> AdjustingExperience { get; set; }
        public Nullable<int> MaximumNumberofClaims { get; set; }
        public Nullable<decimal> MaximumReserves { get; set; }
        public Nullable<int> NationalProducerId { get; set; }
        public string GeographicalAreaofService { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Supervisor { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<decimal> DefaultAdjusterHourlyRate { get; set; }
        public Nullable<decimal> DefaultAdjusterCommissionRate { get; set; }
        public Nullable<bool> IndependenContractorAgreementOnFile { get; set; }
        public Nullable<int> LastYear1099AgreementonFile { get; set; }
        public Nullable<bool> ResumeOnFile { get; set; }
        public string BranchCode { get; set; }
        public string AdjusterBranch { get; set; }
    
        public virtual AdjusterMaster AdjusterMaster { get; set; }
    }
}
