//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjusterLicenseAppointmentType
    {
        public AdjusterLicenseAppointmentType()
        {
            this.AdjusterServiceArea = new HashSet<AdjusterServiceArea>();
        }
    
        public int LicenseAppointmentTypeID { get; set; }
        public string LicenseAppointmentType { get; set; }
        public Nullable<int> ClientID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AdjusterServiceArea> AdjusterServiceArea { get; set; }
    }
}
