//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierInvoiceType
    {
        public CarrierInvoiceType()
        {
            this.CarrierInvoiceProfile = new HashSet<CarrierInvoiceProfile>();
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int InvoiceTypeID { get; set; }
        public string InvoiceType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CarrierInvoiceProfile> CarrierInvoiceProfile { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
