//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims
    {
        public int ClaimsId { get; set; }
        public string Name { get; set; }
        public string PrimeryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string PrimeryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string HearAboutUs { get; set; }
        public string Comments { get; set; }
        public string TypeOfDamage { get; set; }
        public Nullable<int> TypeOfProperty { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string AffectedPropertyAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zip { get; set; }
        public Nullable<decimal> PropertyDamageEstimate { get; set; }
        public Nullable<int> IsPropertyHabitable { get; set; }
        public Nullable<int> CoverageForWing { get; set; }
        public Nullable<int> CoverageForFlood { get; set; }
        public Nullable<int> ReportedToInsurer { get; set; }
        public Nullable<int> SiteLocation { get; set; }
        public Nullable<int> PrimaryProducerId { get; set; }
        public Nullable<int> SecondaryProducerId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string InsertMachineInfo { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateMachineInfo { get; set; }
    }
}
