//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimService
    {
        public int ClaimServiceID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public int ServiceTypeID { get; set; }
        public Nullable<int> AdjusterID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<decimal> ServiceAmount { get; set; }
        public Nullable<decimal> ServiceQty { get; set; }
        public int UserID { get; set; }
        public string Activity { get; set; }
        public string InternalComments { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public Nullable<bool> Billed { get; set; }
    
        public virtual AdjusterMaster AdjusterMaster { get; set; }
        public virtual Claim Claim { get; set; }
        public virtual InvoiceServiceType InvoiceServiceType { get; set; }
        public virtual SecUser SecUser { get; set; }
    }
}
