//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataForm
    {
        public DataForm()
        {
            this.DataFormField = new HashSet<DataFormField>();
            this.DataFormFieldTemplate = new HashSet<DataFormFieldTemplate>();
        }
    
        public int FormID { get; set; }
        public string FormName { get; set; }
    
        public virtual ICollection<DataFormField> DataFormField { get; set; }
        public virtual ICollection<DataFormFieldTemplate> DataFormFieldTemplate { get; set; }
    }
}
