//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentListMaster
    {
        public DocumentListMaster()
        {
            this.LeadDocumentList = new HashSet<LeadDocumentList>();
        }
    
        public int DocumentListId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> PolicyTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> clientID { get; set; }
    
        public virtual ICollection<LeadDocumentList> LeadDocumentList { get; set; }
    }
}
