//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public int ClaimID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToAddress3 { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> InvoiceTypeID { get; set; }
        public Nullable<int> CarrierInvoiceProfileID { get; set; }
        public bool IsVoid { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    
        public virtual CarrierInvoiceProfile CarrierInvoiceProfile { get; set; }
        public virtual CarrierInvoiceType CarrierInvoiceType { get; set; }
        public virtual Claim Claim { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
    }
}
