//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceServiceUnit
    {
        public InvoiceServiceUnit()
        {
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
            this.InvoiceServiceType = new HashSet<InvoiceServiceType>();
        }
    
        public int UnitID { get; set; }
        public string UnitDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual ICollection<InvoiceServiceType> InvoiceServiceType { get; set; }
    }
}
