//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyLimit
    {
        public int PolicyLimitID { get; set; }
        public int PolicyID { get; set; }
        public int LimitID { get; set; }
        public Nullable<decimal> LimitAmount { get; set; }
        public Nullable<decimal> LimitDeductible { get; set; }
        public string CATDeductible { get; set; }
        public string SettlementType { get; set; }
        public Nullable<decimal> ConInsuranceLimit { get; set; }
        public Nullable<decimal> ITV { get; set; }
        public Nullable<decimal> Reserve { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ApplyTo { get; set; }
        public Nullable<bool> ApplyAcrossAllCoverage { get; set; }
        public string WindHailDeductible { get; set; }
        public Nullable<int> ClaimLimitID { get; set; }
        public Nullable<decimal> LossAmountACV { get; set; }
        public Nullable<decimal> LossAmountRCV { get; set; }
        public Nullable<decimal> OverageAmount { get; set; }
    
        public virtual LeadPolicy LeadPolicy { get; set; }
        public virtual Limit Limit { get; set; }
        public virtual ClaimLimit ClaimLimit { get; set; }
        public virtual PolicyLimit PolicyLimit1 { get; set; }
        public virtual PolicyLimit PolicyLimit2 { get; set; }
    }
}
