//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecModule
    {
        public SecModule()
        {
            this.SecModule1 = new HashSet<SecModule>();
            this.SecRoleModule = new HashSet<SecRoleModule>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleDesc { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Url { get; set; }
        public int ModuleType { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> HasNew { get; set; }
        public Nullable<bool> HasEdit { get; set; }
        public Nullable<bool> HasDelete { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedMachineIP { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public string UpdatedMachineIP { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public Nullable<bool> IsSystem { get; set; }
    
        public virtual ICollection<SecModule> SecModule1 { get; set; }
        public virtual SecModule SecModule2 { get; set; }
        public virtual ICollection<SecRoleModule> SecRoleModule { get; set; }
    }
}
