//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecRole
    {
        public SecRole()
        {
            this.SecUser = new HashSet<SecUser>();
            this.SecRoleInvoiceApprovalPermission = new HashSet<SecRoleInvoiceApprovalPermission>();
            this.SecRoleModule = new HashSet<SecRoleModule>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedMachineIP { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public string UpdatedMachineIP { get; set; }
        public Nullable<bool> isClient { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ICollection<SecUser> SecUser { get; set; }
        public virtual ICollection<SecRoleInvoiceApprovalPermission> SecRoleInvoiceApprovalPermission { get; set; }
        public virtual ICollection<SecRoleModule> SecRoleModule { get; set; }
    }
}
