//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLimitOfLiabilityMaster
    {
        public SubLimitOfLiabilityMaster()
        {
            this.LeadPolicy = new HashSet<LeadPolicy>();
        }
    
        public int SublimitLiabilityID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual ICollection<LeadPolicy> LeadPolicy { get; set; }
    }
}
