//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FieldColumn
    {
        public int ColumnID { get; set; }
        public string ColumnName { get; set; }
        public bool isVisible { get; set; }
        public Nullable<int> clientid { get; set; }
    }
}
