//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InvoiceApprovalQueue
    {
        public Nullable<int> ClientID { get; set; }
        public int InvoiceID { get; set; }
        public int ClaimID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToAddress3 { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> InvoiceTypeID { get; set; }
        public Nullable<int> CarrierInvoiceProfileID { get; set; }
        public bool IsVoid { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public string PolicyNumber { get; set; }
        public string AdjusterClaimNumber { get; set; }
        public string InsurerClaimNumber { get; set; }
    }
}
