insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Policy Number')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Insurer Claim ID #')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Adjuster Claim #')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Type of Policy')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Insurance Carrier')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Policyholder')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Policyholder Entity (if any)')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Adjuster')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Supervisor')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Team Lead')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Carrier Owner/Manager Name')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Owner Manager Entity Name')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Severity')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Event Type')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Event Name')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Claim Workflow Type')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Cause of Loss')

--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Status')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Sub Status')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Open/Reported')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date of Initial Reserve Changed')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Assigned')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Acknowledged')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date First Contact Attempted')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Contacted')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Inspection Scheduled')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Inspection Completed')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Submitted')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Indemnity Payment Requested')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Indemnity Payment Approved')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Indemnity Payment Issued')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Closed')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date First Reopen')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Reopen Completed')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date Final Closed')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Cycle Time')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Reopen Cycle Time')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Date of Loss')

insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Property Loss Totals')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Fee Invoice Designation')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Gross Claim Payable')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Casualty Loss Totals')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Net Claim Payable')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Fee Invoice Designation')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Gross Claim Payable')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Depreciation')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Deductible')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Carrier Finance Details(Optional)')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Outstanding Indemnity Reserve')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Outstanding LAE Reserves')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Total Indemnity Paid')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Coverage A Paid')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Coverage B Paid')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Coverage C Paid')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Coverage D Paid')
--insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Total Expense Paid')


insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Outside Adjuster')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Contents Adjuster')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Examiner')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Company Builder')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Company Inventory')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Our Builder')
insert into dbo.DataFormField(FormID,FieldPrompt) values(1,'Inventory Company')



