insert into ImportField(FieldName) values('Insurer Claim ID')
insert into ImportField(FieldName) values('Policy Number')
insert into ImportField(FieldName) values('Policy Form')
insert into ImportField(FieldName) values('Claim Status')
insert into ImportField(FieldName) values('Date of Loss')
insert into ImportField(FieldName) values('Date Reported')
insert into ImportField(FieldName) values('Policy Form')
insert into ImportField(FieldName) values('Date First Closed')
insert into ImportField(FieldName) values('Date First Reopen')
insert into ImportField(FieldName) values('Date Assigned')
insert into ImportField(FieldName) values('Date Acknowledged')
insert into ImportField(FieldName) values('Date First Contact Attempted')
insert into ImportField(FieldName) values('Date Contacted')
insert into ImportField(FieldName) values('Date Inspection Scheduled')
insert into ImportField(FieldName) values('Date Inspection Completed')
insert into ImportField(FieldName) values('Date Submitted')
insert into ImportField(FieldName) values('Date Estimate Uploaded')
insert into ImportField(FieldName) values('Date of Initial Reserve Change')
insert into ImportField(FieldName) values('Date Indemnity Payment Requested')
insert into ImportField(FieldName) values('Date Indemnity Payment Approved')
insert into ImportField(FieldName) values('Date Indemnity Payment Issued')
insert into ImportField(FieldName) values('Date Completed')
insert into ImportField(FieldName) values('Date Closed')
insert into ImportField(FieldName) values('Adjuster Name')
insert into ImportField(FieldName) values('Supervisor Name')
insert into ImportField(FieldName) values('Team Lead Name')
insert into ImportField(FieldName) values('Owner Manager Name')
insert into ImportField(FieldName) values('Owner Manager Entity Name')
insert into ImportField(FieldName) values('Severity')
insert into ImportField(FieldName) values('Event Type')
insert into ImportField(FieldName) values('Event Name')
insert into ImportField(FieldName) values('Cause of Loss Description')
insert into ImportField(FieldName) values('Claim Workflow Type')
insert into ImportField(FieldName) values('Insured Name')
insert into ImportField(FieldName) values('Mailing Address')
insert into ImportField(FieldName) values('Mailing Address2')
insert into ImportField(FieldName) values('Mailing City')
insert into ImportField(FieldName) values('Mailing State')
insert into ImportField(FieldName) values('Mailing Zip')
insert into ImportField(FieldName) values('Mailing County')
insert into ImportField(FieldName) values('Business Phone Number')
insert into ImportField(FieldName) values('Home Phone Number')
insert into ImportField(FieldName) values('Outstanding Indemnity Reserve')
insert into ImportField(FieldName) values('Outstanding LAE Reserves')
insert into ImportField(FieldName) values('Total Indemnity Paid')
insert into ImportField(FieldName) values('Coverage A Paid')
insert into ImportField(FieldName) values('Coverage B Paid')
insert into ImportField(FieldName) values('Coverage C Paid')
insert into ImportField(FieldName) values('Coverage D Paid')
insert into ImportField(FieldName) values('Total Expenses Paid')
insert into ImportField(FieldName) values('Loss Address')
insert into ImportField(FieldName) values('Loss Address2')
insert into ImportField(FieldName) values('Loss City')
insert into ImportField(FieldName) values('Loss State')
insert into ImportField(FieldName) values('Loss Zip')
insert into ImportField(FieldName) values('Loss County')
insert into ImportField(FieldName) values('Adjuster Claim Number')



